version: "3.5"
services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    environment:
      - REDIS_PASSWORD=Bgt56yhNM
      - REDIS_PORT_NUMBER=6379
      - REDIS_EXPIRE_TIME=43200
    ports:
      - 6379:6379
